### ISSUE TITLE
源代码似乎不是UNICODE

### ISSUE THREAD

**Issue by thewonderfulheard** [Chuyu-Team/DirectUI#1]
注释中的汉字是乱码，我的环境是英文版Windows 10

**Comment by mingkuang-Chuyu** [comment]
Hi， 建议你暂时在区域设置的格式中 设置为中文，在未来我一次性全部调整为unicode
 
Date: Wed, 20 Jul 2016 07:47:43 -0700

**Comment by mingkuang-Chuyu** [comment]
我发现Duilib 不同的系统平台 导出都不同，所以此项目打算删除了……
